rvm:
  - 1.9.2
  - 1.9.3
  - jruby-19mode
before_install:
  - gem update --system
  - gem install turn --version 0.8.2
  - gem install turn --version 0.8.3
jdk:
  - openjdk6
gemfile:
  - gemfiles/rails3.0.gemfile
  - gemfiles/rails3.1.gemfile
  - gemfiles/rails3.2.gemfile
branches:
  only:
    - master
