rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - jruby-19mode
before_install:
  - gem update --system
  - gem install turn --version 0.8.2
  - gem install turn --version 0.8.3
jdk:
  - openjdk6
gemfile:
  - gemfiles/3.0.20.gemfile
  - gemfiles/3.1.11.gemfile
  - gemfiles/3.2.12.gemfile
  - gemfiles/3.2.13.rc2.gemfile
matrix:
  exclude:
    - rvm: 2.0.0
      gemfile: gemfiles/3.0.20.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/3.1.11.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/3.2.12.gemfile
branches:
  only:
    - master
