language: ruby
before_install:
  - gem update --system
cache: bundler
rvm:
  - 2.1.5
  - 2.2.1
  - jruby-19mode
jdk:
  - openjdk6
branches:
  only:
    - master
install:
  - "travis_retry bundle install"
gemfile:
  - gemfiles/rails3.2.gemfile
  - gemfiles/rails4.1.gemfile
  - gemfiles/rails4.2.gemfile
